# Generated by Django 6.1.1 on 2026-09-14 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_sale_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The single Technical Manager assigned to this project on sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
