# Generated by Django 6.1.1 on 2026-09-07 15:06

from django.db import migrations


ROLES = [
    "Super Admin",
    "Business Developer",
    "Technical Manager",
    "Engineer",
]


def create_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for role in ROLES:
        Group.objects.get_or_create(name=role)


def remove_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=ROLES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),  
        ("auth", "0012_alter_user_first_name_max_length"),  
    ]

    operations = [
        migrations.RunPython(create_roles, remove_roles),
    ]