# Generated by Django 6.1.1 on 2026-09-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField(blank=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_contact', models.CharField(max_length=50)),
                ('platform_used', models.CharField(max_length=100)),
                ('test_type', models.CharField(choices=[('test_project', 'Test Project'), ('interview', 'Interview')], max_length=20)),
                ('comments_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sale', 'Sale'), ('no_sale', 'No Sale')], default='open', max_length=20)),
                ('sale_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('sale_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('test_project', 'Test Project'), ('interview', 'Interview')], max_length=20)),
                ('status', models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('pending_reassignment', 'Pending Reassignment'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending_acceptance', max_length=25)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases_created', to=settings.AUTH_USER_MODEL)),
                ('current_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases_managed', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='leads.lead')),
            ],
            options={
                'ordering': ['lead', 'order'],
                'unique_together': {('lead', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PhaseEngineerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('marked_done', 'Marked Done')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_engineer_history_entries', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_engineer_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_history', to='leads.phase')),
            ],
            options={
                'verbose_name_plural': 'Phase engineer histories',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseManagerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_manager_history_entries', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(help_text='Who triggered this action — BD (assigned) or the manager themself (accepted/declined)', on_delete=django.db.models.deletion.PROTECT, related_name='phase_manager_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_history', to='leads.phase')),
            ],
            options={
                'verbose_name_plural': 'Phase manager histories',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('done', 'Done')], default='pending', max_length=20)),
                ('assigned_by', models.ForeignKey(help_text='The technical manager who added this engineer to the phase', on_delete=django.db.models.deletion.PROTECT, related_name='engineers_assigned', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_assignments', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_engineers', to='leads.phase')),
            ],
            options={
                'unique_together': {('phase', 'engineer')},
            },
        ),
    ]
