# Generated by Django 6.1.1 on 2026-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_phase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='test_type',
            field=models.CharField(blank=True, choices=[('test_project', 'Test Project'), ('interview', 'Interview')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='type',
            field=models.CharField(choices=[('test_project', 'Test Project'), ('interview', 'Interview')], max_length=20),
        ),
    ]
