# Generated by Django 6.1.1 on 2026-09-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('phase_assigned', 'Phase Assigned'), ('phase_accepted', 'Phase Accepted'), ('phase_declined', 'Phase Declined'), ('phase_completed', 'Phase Completed'), ('engineer_assigned', 'Engineer Assigned'), ('engineer_declined', 'Engineer Declined'), ('lead_created', 'New Lead Created'), ('lead_sale', 'Lead Marked as Sale'), ('lead_no_sale', 'Lead Marked as No Sale'), ('project_assigned', 'Project Assigned')], max_length=30),
        ),
    ]
